### ISSUE TITLE
[BUG] Mod don't load

### ISSUE THREAD

**Issue by MaoDoBan** [samolego/FabricTailor#1]
I'm using fabrictailor-1.0.0.jar with fabric-api-0.14.1+build.372-1.16.jar in fabric loader 0.8.9+build203.
Minecraft crash on loading.
Crash report:
[crash-2020-07-03_00.44.34-client.txt](https://github.com/samolego/FabricTailor/files/4867664/crash-2020-07-03_00.44.34-client.txt)

**Comment by samolego** [comment]
`Caused by: java.lang.ClassNotFoundException: nerdhub.cardinal.components.api.component.Component`

Did you install Cardinal Components API?

**Comment by MaoDoBan** [comment]
No. Sorry for this.
