### ISSUE TITLE
[BUG] /skin set player <playername> always uses the compact model when server is in offline mode.

### ISSUE THREAD

**Issue by LIME-S** [samolego/FabricTailor#10]
the /skin set player command could use the wrong model, if you are in offline mode.

**Comment by samolego** [comment]
Humm, this is strange, since API used is the same. Could you tell the player you were testing it with?

**Comment by LIME-S** [comment]
/skin set player Emhl (it's my own account)

**Comment by samolego** [comment]
Oh, I read it wrong ... Wdym by `could use the wrong model`? Model doesn't depend on the status of the server. It depends on skin model saved in mojang skin DB.

**Comment by LIME-S** [comment]
I use the slim model for my skin. but /skin set player Emhl always displays it with the classic model.

**Comment by samolego** [comment]
I think it's a problem with ely.by API. There's probably an account with same name there. You could try contacting them, as their [TOS](https://account.ely.by/rules) (rule 5) means that you can request to restore your username.

Alternatively, you can do

`/skin set URL slim http://textures.minecraft.net/texture/ba31432c44cb9db77a58c6a4d78555180fb3dbd73353320d5bf95f28bec86704`
