### ISSUE TITLE
[BUG] Crash on Server Join - 1.20.6

### ISSUE THREAD

**Issue by snowzzrra** [samolego/FabricTailor#103]
## Issue

- [ X ] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

Whenever I join my SMP server, it would disconnect and send a error message. It only happened whenever Fabric Tailor was installed.

**To Reproduce**

1. Install Fabric Tailor on client and server
2. Try to join

**Logs**

[Log with other mods.](https://pastebin.com/wYyphzXV)

*Are you using any other mods?*

Tried with other mods, tried without other mods, same problem.

**Comment by samolego** [comment]
> io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (fabrictailor:hello)

I've seen this mentioned in discord. Please remove fabrictailor from your client atm

**Comment by snowzzrra** [comment]
sure, would it still work server only or would the error repeat itself?

**Comment by samolego** [comment]
Yeah, sever only works fine

**Comment by YkVox** [comment]
can reproduce the issue here
good luck fixing it samolego !

**Comment by sternschnaube** [comment]
Thanks 😄
