### ISSUE TITLE
A /cape command

### ISSUE THREAD

**Issue by sadlyborger** [samolego/FabricTailor#104]
Instead of downloading also in client, would it be possible to have /cape command and allow us to change the cape base on servers cape folder or we can use the mojangs cape link. Example : https://minecraft.wiki/images/Mojang_Classic_Cape_%28texture%29.png?4a4e7&format=original

**Comment by samolego** [comment]
tldr: No, sadly not.

Longer explanation:
Minecraft skin system works by delivering information about specific player's skin to client. That skin info includes cape.
Fabrictailor "injects" its data to skin info to get the cape working, but at a cost - skin info is not signed by Mojang anymore (aka client knows somebody made modifications to skin) so it refuses to show the new skin + cape.
If fabrictailor is installed on client though, it accepts the data.

**Comment by sadlyborger** [comment]
Thank you very much. 🙇 
That explains it.
