### ISSUE TITLE
[BUG] entering invalid url into cape url section causes game crash

### ISSUE THREAD

**Issue by RoverBot-Dev** [samolego/FabricTailor#111]
## Issue

- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

game crashes when cape url is invalid and there is no way to reset the cape url

**To Reproduce**

1. enter a wrong url or text into the cape url section
2. game crashes and same when loading into a world

**Comment by samolego** [comment]
Please post logs & edit the issue title.

**Comment by RoverBot-Dev** [comment]
[2024-08-10-5.log](https://github.com/user-attachments/files/16639236/2024-08-10-5.log)
I forgot to change issue name
here's log

**Comment by CeasingBonsai17** [comment]
any clue if that could be related to the issue of my skin resetting when i type a url into the cape thing?

**Comment by samolego** [comment]
Should be fixed now.
