### ISSUE TITLE
[BUG] Cannot set skin via URL

### ISSUE THREAD

**Issue by renhiyama** [samolego/FabricTailor#116]
No matter what type of url I use, like `https://static.planetminecraft.com/files/resource_media/skin/skinseedskin-1646852037483-15482743.png` or anything like that, it warns me saying "You have to provide URL, player name ...."

In server logs, I see:
```
[FabricTailor] An error occurred: https:/static.planetminecraft.com/files/resource_media/skin/skinseedskin-1646852037483-15482743.png
```

I see the extra forward slash being removed, no matter what I try. I think its a bug on your end, maybe like youre convert the string to a file url, which is known to remove double slashes according to UNIX file urls. Maybe have a priority based if else condition that specifically checks for "https://" startsWith case, and straight away download via that way.

**Comment by MGJerry** [comment]
Tested with command: /skin set URL classic https://static.planetminecraft.com/files/resource_media/skin/skinseedskin-1646852037483-15482743.png
![2024-09-17_23 28 22](https://github.com/user-attachments/assets/55342ccc-04b0-43ad-b29f-7bcf12bf8294)

Please check if you used the correct syntax: 
* /skin set URL classic (url here) for full-width/steve skin
* /skin set URL slim (url here) for slim/alex skin
