### ISSUE TITLE
[BUG] You have to provide URL, player's name or file of skin you want.

### ISSUE THREAD

**Issue by kiberptah** [samolego/FabricTailor#117]
## Issue

- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

When skin_change_timer is set to -1 attempt to change skin (skin set URL) quickly after the previous change results in error "You have to provide URL, player's name or file of skin you want.". I use the same command that worked before (chat - up arrow). After waiting a couple of seconds it changes successfully with the same command. I change skin with URL, file is on the same server that my minecraft server runs on. 

It is not reproducible when using "skin set player", only with URL apparently.

**To Reproduce**

1. Change skin with /set skin URL classic <url>
2. After skin changes quickly use command again (url can be the same or different)
3. Observe the error

**Logs**

If you have any errors, please paste them as well. If possible, please use pasting site.

Yes, but they do not touch skins and I don't have reasons to believe they affect this, mods are mostly for server commands and some specific changes to gameplay (e.g. better combat)

**Additional context**

Tried with URLs of skins stored on my server and with 3rd party skin websites just to test, same result. I don't have reasons to believe it is some error on my server, but even if it is so, error should reflect it.

**Comment by kiberptah** [comment]
with skin_change_timer set to >0 issue also reproducible, and it is not the same error that show if trying to change before timeout.

**Comment by samolego** [comment]
![Screenshot_20241016_213906](https://github.com/user-attachments/assets/0083a5d0-7caf-4add-b8bd-3704382f950d)
Cannot reproduce

**Comment by kiberptah** [comment]
> ![Screenshot_20241016_213906](https://private-user-images.githubusercontent.com/34912839/377206387-0083a5d0-7caf-4add-b8bd-3704382f950d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMDc5OTUsIm5iZiI6MTcyOTEwNzY5NSwicGF0aCI6Ii8zNDkxMjgzOS8zNzcyMDYzODctMDA4M2E1ZDAtN2NhZi00YWRkLWI4YmQtMzcwNDM4MmY5NTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE5NDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMzVkNmEyNTYyNmE5MzkyZjE1N2JlM2JmYzY3ZGViOTc2YzFlOTYyODI1NTU2Nzk5Y2IxNDk3NDU0Nzc1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Czp2onQMcMUtSAiS5Z4COzifpgA0ZaSArEW1mhnew0g) Cannot reproduce

What about 0 seconds timer?

**Comment by samolego** [comment]
![Screenshot_20241016_215650](https://github.com/user-attachments/assets/fc9c1349-f587-48cf-a120-ddac71f66d94)
That's with 0 seconds.

**Comment by samolego** [comment]
Should be working in 2.5.2
