### ISSUE TITLE
[BUG] Doesn't work on servers

### ISSUE THREAD

**Issue by Oregano1963** [samolego/FabricTailor#118]
## For skin fetching problems
- [x] I have tried generating skin manually on [mineskin.org](https://mineskin.org/) and it works there.

## Issue

- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

The clientside skin won't render on servers but rather would show the actual skin.

**To Reproduce**

1. Set custom skin
2. Go on a server with this mod (in my case, Hypixel)
3. Go into f5 mode

**Logs**

https://mclo.gs/iRSIjlP

*Are you using any other mods?*
I'm using the Asphalt modpack

**Additional context**

It works fine on singleplayer

**Comment by samolego** [comment]
Skin is based per world, not for the whole client. You'd need to use a server that has fabrictailor installed.
