### ISSUE TITLE
[BUG] Snapshot Curseforge Uploads End With "Snaspshot" [sic] Suffix

### ISSUE THREAD

**Issue by solonovamax** [samolego/FabricTailor#122]
## Issue

- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

Uploads to curseforge end with the "-Snaspshot" [sic] suffix.
This is a typo in your buildscript.

small typo lol

**Comment by solonovamax** [comment]
Also, in your buildscript I noticed that you used `file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar")` a few times. you can actually swap this out with `jar.archiveFile`, and it will give you the output jar file.
However, it's probably best to instead use `remapJar.archiveFile`, as although the jar is remapped in-place, this would add a task dependency on the `remapJar` task.

**Comment by samolego** [comment]
Thanks :)
