### ISSUE TITLE
[BUG] Skin change reported as successful, but the default skin is still present

### ISSUE THREAD

**Issue by gelvetica** [samolego/FabricTailor#125]
## For skin fetching problems
- [x] I have tried generating skin manually on [mineskin.org](https://mineskin.org/) and it works there.

## Issue

- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

When trying to set my skin using any method, the mod reports that it was successful, but my skin has not changed from the default.

**To Reproduce**

1. attempt to change skin using any method on /skin
2. see that it hasnt changed
3. retrieve a napkin to wipe the tears that have streamed onto your keyboard

**Logs**

no errors on client or server

*Are you using any other mods?*
```
cloth-config-11.1.136-fabric.jar
CreativeCore_FABRIC_v2.12.14_mc1.20.1.jar
dcintegration-fabric-3.0.7-1.20.1.jar
easyauth-mc1.20-3.0.19.jar
emotecraft-for-MC1.20.1-2.2.7-b.build.50-fabric.jar
fabric-api-0.92.2+1.20.1.jar
fabrictailor-2.1.2.jar
sit-1.20.1-27.jar
waterframes-FABRIC-mc1.20.1-v2.1.6.jar
watermedia-2.0.75.jar
worldedit-mod-7.2.15.jar
```

**Additional context**

fabric-server-mc.1.20.1-loader.0.16.9-launcher.1.0.1

**Comment by samolego** [comment]
TLauncher is not supported since it has its own skin system that overrides fabrictailor's.

**Comment by gelvetica** [comment]
Apologies, I misread the form. I am using Prism Launcher with an online account. EasyAuth is installed to the server because I'm implementing bots that need to be able to use an offline account.

**Comment by samolego** [comment]
Ah, ok. Can you reproduce it without other mods?

**Comment by samolego** [comment]
Shouldn't be the case at fabrictailor's side regarding cache. Anyway, is it working now?

If it keeps happening, perhaps try reporting to easyauth too? Although I am not sure they do anything with skins :/ ...

**Comment by gelvetica** [comment]
Everything is working now, I really don't know what was causing the issue. I'll report this to EasyAuth.
