### ISSUE TITLE
[BUG] It don't work

### ISSUE THREAD

**Issue by LeoPYDevel** [samolego/FabricTailor#126]
## For skin fetching problems
- [ ] I have tried generating skin manually on [mineskin.org](https://mineskin.org/) and it works there.

## The MOD Don't work

- [x] I'm not using TLauncher, i use SKLauncher in Windows 10

**Describe the bug**

When i try to change my skin (with a url, local o name) it says "Skins changed" But i don't see any change, the mod updates my skin, but my skin turn to my default skin

**Comment by samolego** [comment]
> Easy skin and cape management
>
> Manage your in-game look through our website. Once you have logged in, you will have access to the personalisation view, where you can easily upload your own skin and cape. If you don't have one, you can always use the skins and capes we have prepared - assigning them to your account is just a few clicks away. And it's all for free.

SKLauncher seems to be doing some skin stuff, might be the same as TLauncher problem.

**Comment by LeoPYDevel** [comment]
I had a mod that used to give me the same issue. However, it had an option labeled "Disable Minecraft API," and enabling it completely fixed the problem. It seems like the launcher or mod bypasses certain API checks when this setting is activated
