### ISSUE TITLE
Skin URL Error

### ISSUE THREAD

**Issue by modlover** [samolego/FabricTailor#14]
I am a user who uses this mod while playing Minecraft.
And I just installed it now, and I couldn't load my skin by URL. 
What specific URL I have to put in the command? 
For example, I tried to load a skin from http://minecraft.novaskin.me/gallery and https://www.minecraftskins.com/3/ but it is not working...what specific site can I put in the command? 
Is it only working from using URLs from minecraft.net?

**Comment by samolego** [comment]
It should work from any skin site, just make sure you provide a valid url (*usually* ending with `.png`).

I guess you've figured it out already.

**Comment by Mapahce2213** [comment]
Hello, i have same problem.

`/skin set url https://i.imgur.com/aaWqmK3.png`

<img width="644" height="130" alt="Image" src="https://github.com/user-attachments/assets/ef9738f6-c17b-400f-82a4-48605d8aa4f8" />
