### ISSUE TITLE
Don't work when using BungeeCord proxy

### ISSUE THREAD

**Issue by luvletter2333** [samolego/FabricTailor#16]
Environment:
- server 1.16.5 with fabric loader 0.11.1
- mod list:
  - bettersleeping-0.4.0.jar
  - carpet-extra-1.16.2-1.4.8.jar
  - fabric-api-0.30.0+1.16 (1).jar
  - fabric-carpet-1.16.5-1.4.26+v210210.jar
  - FabricProxy-1.4.6.jar
  - fabrictailor_fabric-1.4.0-1.16.4.jar
  - FabricTPA-1.4.1.jar
  - lithium-fabric-mc1.16.5-0.6.3.jar
  - phosphor-fabric-mc1.16.3-0.7.0+build.10.jar
- FabricProxy config:
> BungeeCord = true
> BungeeCordWorkaround = true
> Velocity = false
> allowBypassProxy = true
> secret = ""

- BungeeCord
- Enabled BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:3d701fb:1545
- plugins:
  - Geyser 1.2.0-SNAPSHOT (git-master-b16e1d6)
- config:
prevent_proxy_connections: false

> listeners:
> - query_port: 25577
>   motd: '&1Another Bungee server'
>   tab_list: GLOBAL_PING
>   query_enabled: false
>   proxy_protocol: false
>   forced_hosts:
>     pvp.md-5.net: lobby
>   ping_passthrough: true
>   priorities:
>   - lobby
>   bind_local_address: true
>   host: 0.0.0.0:25577
>   max_players: 10
>   tab_size: 60
>   force_default_server: false
> remote_ping_cache: -1
> network_compression_threshold: 256
> permissions:
>   default:
>   - bungeecord.command.server
>   - bungeecord.command.list
>   admin:
>   - bungeecord.command.alert
>   - bungeecord.command.end
>   - bungeecord.command.ip
>   - bungeecord.command.reload
> log_pings: true
> connection_throttle_limit: 3
> server_connect_timeout: 5000
> timeout: 30000
> player_limit: -1
> ip_forward: true
> groups:
>   md_5:
>   - admin
> remote_ping_timeout: 5000
> connection_throttle: 4000
> log_commands: false
> stats: 11111111-4444-ffff-22222-33333333333
> online_mode: false
> forge_support: true
> disabled_commands:
> - disabledcommandhere
> servers:
>   lobby:
>     motd: '&1Just another BungeeCord - Forced Host'
>     address: 127.0.0.1:25565
>     restricted: false

Login into Fabric, mod works flamelessly.

Login into BungeeCord (Java Edition), cannot change skin and the skin is always Steve, even not the skin of the player's ID (online).

BungeeCord Bedrock(provided by Geyser) not tested yet

**Comment by samolego** [comment]
I'm sorry to reply late.
> Login into Fabric, mod works flamelessly.

FabricTailor works only on Fabric, BungeeCord is sadly not supported really.

if I understand you correctly, your BungeeCord connects you to the Fabric server (where `/skin` works), but after going back to the "main" server (gosh I really need to take a look at how BC works) skin is not loaded? This is kinda expected ..?
