### ISSUE TITLE
[BUG] Mod makes Origins mod origin selection dialog not appear the first time you join. 

### ISSUE THREAD

**Issue by J3LL4** [samolego/FabricTailor#18]
**Describe the bug**
In Origins mod, players on the first time joining their game can select their origin ( or other class-like stuff ). 
For some reason, with this mod installed, the selection doesn't appear the first time, only the second.
**To Reproduce**
1. Install Origins mod with fabrictailor
2. Run a world
3. The selection doesn't show up
4. When you get out and back in, the selection appears.

**Are you using any other mods?
Origins mod

**Comment by samolego** [comment]
Hi, thanks for the report, I'll take a look into it when I have time :).
