### ISSUE TITLE
[ENHANCEMENT] Config to disallow copying a player skin

### ISSUE THREAD

**Issue by Merith-TK** [samolego/FabricTailor#19]
Basically I want to have this added to an SMP i am on for lore reasons (so players dont have to log in/out all the time)

But the admins have brought up the concern about pretending to be another player, becaus ewe have `noplayerlabels` installed which disables players usernames above their head.

So could you add a config option to just, not allow copying a players skin?

**Comment by samolego** [comment]
Doesn't sound too hard to implement, but they can still use URL option and get admin skin that way ...

**Comment by Merith-TK** [comment]
yeah, but it certainly is a deterant, so if they try to copy the skin first, they will get a warning basically saying "hey, this isnt allowed, dont do this"

**Comment by samolego** [comment]
> if they try to copy the skin first

This can be done with online tools, how are you going to detect it?

Thinking about this, LuckPerms support might be better than the config as well.

**Comment by Merith-TK** [comment]
True, right now i am proposing a modified version of the mod to the admins that straight up, disable `/skin set username`

I mean, the minecraft skin is a standardized format, so in theory to ENSURE that people dont steal other skins, we can potentially implement something that converts the 64x64 image to an array? and compare the "/skin set" skin to a online player?

**Comment by samolego** [comment]
Humm, that would be a possible way to do it, but if people really want admin skin they can simply change a pixel and the whole system breaks ...

**Comment by Merith-TK** [comment]
Not of we set it so a a skin can be blocked if it has a similarity level.
Where if a certain amount of pixels in the array are the same, it can be
blocked.

**Comment by samolego** [comment]
After some further thinking, this is not something I'd spend my time on implementing. Sorry :|

**Comment by Merith-TK** [comment]
If I were to implement it myself, would you accept a PR?

**Comment by samolego** [comment]
Yes, I'm open to PRs :)
