### ISSUE TITLE
[BUG] Mod makes resource pack dialog not appear

### ISSUE THREAD

**Issue by Londiuh** [samolego/FabricTailor#20]
**Describe the bug**
When I use this mod the resource pack prompt dialog doesn't appear.

**To Reproduce**
1. Add a server resource pack in `server.properties`
2. Install FabricTailor
3. Start the server
4. Join the server and resource pack dialog won't appear

**Are you using any other mods?
Tested with and without mods and I got the same result

**Additional context**
Maybe related with #18 (?)

**Comment by samolego** [comment]
Hi, thanks for reporting!
It's strange as mod doesn't change any login sequence 🤔 ... I'll take a look when I have time.

**Comment by Londiuh** [comment]
This may be caused by `reloadSkin()`. When I join with a name that doesn't exist the mod can't fetch the skin and the resource pack dialog appears, but if I set a skin, the resource pack dialog doesn't appear again.

**Comment by samolego** [comment]
Yeah, that is very likely then. I should probably choose a different target for player join event.

**Comment by DillonB07** [comment]
I disagree.
I use FabricTailor on my server with a custom resource pack and it all works fine.
Are you sure you added the resource pack properly? 
I know this was an issue from a long time ago but I am commenting as it is still open.

**Comment by samolego** [comment]
Should be fixed now.
