### ISSUE TITLE
[Suggestion] /cape?

### ISSUE THREAD

**Issue by AxoCode** [samolego/FabricTailor#21]
The syntax pretty much the same, but its applying cape instead of skins.

**Comment by samolego** [comment]
This would be possible client side only, so it's not the highest priority. It will be implemented after #12 and #22 , if I have time and motivation.

**Comment by barraIhsan** [comment]
Oh also, if we in server for example, and other people also have the client, can they see my cape? I think its possible, just like the [CustomSkinLoader](https://www.curseforge.com/minecraft/mc-mods/customskinloader)

**Comment by samolego** [comment]
No, the way it would be implemented other players wouldn't see the cape, as you'd need a cape server otherwise.

**Comment by barraIhsan** [comment]
But why the CustomSkinLoader mod thing can do that? Is that different?

**Comment by samolego** [comment]
CustomSkinLoader uses online services afaik, so all the clients get the info about the cape. At least I think so.

**Comment by samolego** [comment]
implemented in 2.0.0 (via GUI)
