### ISSUE TITLE
[BUG] Alex Head

### ISSUE THREAD

**Issue by Blueil** [samolego/FabricTailor#24]
**Describe the bug**
I have a datapack that will drop the head when a player dies, but when it should drop the player's head, it drops a alex head if the player doesn't set their skin.

**To Reproduce**
1. Install a datapack that making player drop their head when he dies.
2. Do /skin clear to make sure that you don't have a skin on with this mod.
3. Kill yourself

**Logs**
If you have any errors, please paste them as well. If possible, please use pasting site.

**Are you using any other mods?
fabric carpet
carpet extras
fabric api
lithium fabric
phosphor fabric
simple auth

**Additional context**

**Comment by samolego** [comment]
This is the intended behaviour? `/skin clear` clears your skin so it defaults to Steve or Alex, dependind on uuid hash.
