### ISSUE TITLE
[BUG] Can't upload a skin from file

### ISSUE THREAD

**Issue by mantevian** [samolego/FabricTailor#25]
**Describe the bug**
When running the mod on a server, `/skin set upload <path>` only properly works once after opening a world. To get it to work again you need to restart the server.

**To Reproduce**
1. Set up a `skins` folder in your multiplayer server and upload a `.png` skin into it.
2. Start the server and type `/skin set upload skins/[name].png` which will work properly and set your skin to the one from the file.
3. Clear your skin and repeat step 2, and you'll get an error saying "A problem occured when trying to upload the skin".

**Logs**
The mod hasn't logged anything - not on success nor failure of uploading a skin.

**Are you using any other mods?**
Yes, some optimization/quality of life mods, specifically: Custom Spawn, Fabric Carpet, Chunk Pregenerator, Discord Link, FerriteCore, Krypton, LazyDFU, Lithium, Overworld Two, Random Patches, Starlight and WorldEdit.

**Comment by samolego** [comment]
Hi, thanks for reporting. Have you tried uploading the skin file to [mineskin](mineskin.org)? Does it work there?

**Comment by mantevian** [comment]
Just tried it out - the same thing happens. It properly works the first time, and on any next attempt it responds with "Malformed url" even though I'm absolutely sure I'm entering the same URL.

**Comment by samolego** [comment]
It's a mineskin bug then sadly ... I doubt I can do anything about it ... :(

**Comment by mantevian** [comment]
But what about the local file thing? Does it somehow use mineskin?

**Comment by samolego** [comment]
Yes, it goes through mineskin as well, as it needs Mojang signature.
