### ISSUE TITLE
License on Modrinth page is incorrect

### ISSUE THREAD

**Issue by wafflecoffee** [samolego/FabricTailor#27]
The license for this project is LGPL-3.0, but [your Modrinth page](https://modrinth.com/mod/g8w1NapE) says `CUSTOM`. Could this be changed to accurately reflect the license as `LGPL-3.0`? :)

**Comment by samolego** [comment]
Thanks, I probably searched for `lgpl` instead of `gnu lesser ...` and didn't find it :P ...
