### ISSUE TITLE
[FEATURE] Set cape.

### ISSUE THREAD

**Issue by baduhai** [samolego/FabricTailor#3]
It'd be nice if it were possible to set capes in addition to skins by using `/cape`. If I were to open a pull request for this, would you be interested?

**Comment by baduhai** [comment]
I don't have much experience with java, but I'll read up on the Fabric API and see what I can do. In the meanwhile, I've found a Forge mod that allows setting the cape and can be run on servers: [SkinChanger](https://github.com/edoren/SkinChanger).

**Comment by samolego** [comment]
Looking at the source code,
https://github.com/edoren/SkinChanger/blob/9e50afc372f5d481950f445b8425c9338bf76b2c/src/main/java/me/edoren/skin_changer/server/ServerController.java#L24

doesn't seem to include any cape info (commands, etc.)

**Comment by samolego** [comment]
Humm, I've checked out the source but at the first glance I don't really get how cape loading works :).

However, it is strange to me that there's no cape plugin for bukkit / spigot /paper ...

**Comment by baduhai** [comment]
Yeah, I got nothing on my end. While I understand more or less how your mod works, I don't understand how the other one sets the Cape.
