### ISSUE TITLE
[BUG] /skin set player <playername> has abnormal behavior

### ISSUE THREAD

**Issue by Derpitron** [samolego/FabricTailor#30]
When using FabricTailor 1.5.1 for 1.17, using `/skin set player <playername>` has different unintended effects.
First, i tried to run `/skin set player Derpitron` (my name) 
![image](https://user-images.githubusercontent.com/46134462/121808221-17f36880-cc75-11eb-92f3-910b7ea4e028.png)

and it did not work. Then, I tried random names like Technoblade, Dream and DanTDM, all of which worked as expected and set the skin properly.

after that I tried to run `/skin set player Derpitron` again which had a different effect.
![image](https://user-images.githubusercontent.com/46134462/121808297-5e48c780-cc75-11eb-9179-e26c71f12994.png)
the skin says it was set, but my skin did not change from DanTDM's skin to mine at all.

When I relogged, the skin reset back to Steve. this happened both when I set the skin as DanTDM normally and my name. I also tried a few other names like my friend's names but it did not work, similar to Derpitron. the effects were different depending on the player's name.

I am assuming that the mod is pulling skins from a website that has celebrities skins stored but not regular skins. Please fix this as soon as possible, as we are playing on an offline server and I cannot always access the mods/config files.

**Comment by samolego** [comment]
Humm, it might be related to the fact that you're running offline mode server. Not sure about it, did it happen on 1.16? As there were some changes I made to skin fetching ...

Saving is related to #29 .

**Comment by Derpitron** [comment]
I am running on an offline mode server. and no, this bug did not happen on 1.16.5, actually none of these bugs happened

**Comment by brenodantas10** [comment]
Okay, this bug is happening to me now in 1.16.5. Server set to offline, can set skin to famous players but not me...
