### ISSUE TITLE
[BUG] Unable to set skin using Player Name option

### ISSUE THREAD

**Issue by Derpitron** [samolego/FabricTailor#33]
Using both the client GUI and server command on FabricTailor 1.6.1, I am unable to set the skin using a player name.

It returns an error saying "this player has no skins saved".

![image](https://user-images.githubusercontent.com/46134462/122635563-53bd8080-d102-11eb-96ef-77e57f3d03dd.png)
![image](https://user-images.githubusercontent.com/46134462/122635416-71d6b100-d101-11eb-8fd4-ddc6a68cf8de.png)

![image](https://user-images.githubusercontent.com/46134462/122635423-7dc27300-d101-11eb-9a45-25521d7a2489.png)
![image](https://user-images.githubusercontent.com/46134462/122635426-831fbd80-d101-11eb-8c4e-25ece2b6a26d.png)

I am assuming that the error is because the player specified does not have their skins saved on whatever skin repo, collection, or mirror you're pulling from

**Comment by camiobete** [comment]
yes the same thing is happening with me

**Comment by TerminalHash** [comment]
+1. It's not working yet.

**Comment by samolego** [comment]
Fixed in 6781b9191a10006d3c4022add4463a116818fc1b
