### ISSUE TITLE
[BUG] The game crashes after changing skin with Taterzens installed 

### ISSUE THREAD

**Issue by ImSpaceLover** [samolego/FabricTailor#38]
When you try to use any /skin command with Taterzens installed, the game crashes.
Here's a crashlog: [crash-2021-08-11_19.02.20-client.txt](https://github.com/samolego/FabricTailor/files/6969824/crash-2021-08-11_19.02.20-client.txt)

To reproduce:
Join the game and write /skin set player Jeb_

**Comment by samolego** [comment]
Fixed in 1.6.2
