### ISSUE TITLE
[BUG] Crash when loading a world

### ISSUE THREAD

**Issue by Leeo97one** [samolego/FabricTailor#4]
**Describe the bug**
The game crashes right after loading a world.

**To Reproduce**
1. Load a world

**Logs**
[latest.log](https://github.com/samolego/FabricTailor/files/5425925/latest.log)
[crash-2020-10-22_23.23.53-client.txt](https://github.com/samolego/FabricTailor/files/5425927/crash-2020-10-22_23.23.53-client.txt)

**Are you using any other mods?**
Fabric API

**Comment by samolego** [comment]
Hi, thanks for reporting. This is obviously a bug, I'll look into it.

**Comment by samolego** [comment]
This should be fixed in 1.3.1
