### ISSUE TITLE
[BUG] Unable to upload a skin via URL

### ISSUE THREAD

**Issue by axelnieves2012** [samolego/FabricTailor#40]
These are the commands I used: 
/skin set URL classic "http://axelmod.great-site.net/minecraft/fluttershy.png"
/skin set URL classic http://axelmod.great-site.net/minecraft/fluttershy.png
/skin set URL slim "http://axelmod.great-site.net/minecraft/fluttershy.png"
/skin set URL slim http://axelmod.great-site.net/minecraft/fluttershy.png

I got this return:
Trying to set the skin ... Please wait.
This player doesn't seem to have any skins saved.

And nothing happens.
Of couse, I also tried to use different skins:
/skin set URL classic "http://axelmod.great-site.net/minecraft/twilight1.png"
/skin set URL classic "http://axelmod.great-site.net/minecraft/twilight2.png"
/skin set URL classic "http://axelmod.great-site.net/minecraft/sailormoon.png"

All of them, with and without quotes, 
all of them either classic and slim.
And nothing worked.

I also tried to upload them from my local drive and it kept not working until I was writing this.

**Comment by samolego** [comment]
> This player doesn't seem to have any skins saved.
Huh, seems like wrong method is getting called ...

**Comment by samolego** [comment]
Just checked on mineskin.org - it's a problem on their end

**Comment by axelnieves2012** [comment]
I did not understand what was the problem. Do you mean the problem is my web server?
Yesterday I installed XAMPP on my PC, so I do have a new server to make the same tests, but maybe it could be done on this weekend. I am too busy this week.

**Comment by samolego** [comment]
It's nothing I can do about, FabricTailor uses mineskin api and you cannot even upload skin from that url there. Try contacting them instead.
