### ISSUE TITLE
Mod is picking up wrong person/skin

### ISSUE THREAD

**Issue by nachoggamer** [samolego/FabricTailor#41]
I don't know what's happening but whenever I do /skin set player NachoGGamer or using the menu from the mod it returns a different skin from the one I use, and also doesn't show my cape.

fabric server/ singleplayer 1.17
[mine.ly/NachoGGamer.2](url)

**Comment by samolego** [comment]
Mod currently uses an unofficial skin API. Migrating to mojang one is on the todo list :)

**Comment by nachoggamer** [comment]
I checked the ely.by site and there is none that matches the one that shows up in game

**Comment by samolego** [comment]
Fixed in 6781b9191a10006d3c4022add4463a116818fc1b
