### ISSUE TITLE
[BUG] Skin not applied

### ISSUE THREAD

**Issue by grebwsthw** [samolego/FabricTailor#45]
**Unable to fetch skin**

For some reason, I am unable to fetch my skin. Tried setting my minecraft username, tried uploading file path, tried getting url from mineskin, but im still steve for some reason. The server is vanilla and doesnt have fabric installed, could that be the issue? Version is 1.18

**To Reproduce**

1. Make vanilla server
2. Try to fetch skin

*Are you using any other mods?*
I am using Xaero's Minimap, Xaero's World Map, Sodium, ToroHealth Damage Indicators, Iris Shaders, Fabric API

**Comment by samolego** [comment]
Which launcher? Does it say that "skin was fetched"?

**Comment by samolego** [comment]
Oh wait, you're using vanilla server; this mod needs to be installed on server (but doesn't require clients to have it)

**Comment by samolego** [comment]
To fix this, simply use Fabric server and install fabrictailor there :) (you can also use some other mods to speed up the server without compromising game mechanics like in paper - use Lithium mod)
