### ISSUE TITLE
Feature: use a configurable server for skins

### ISSUE THREAD

**Issue by MeeniMc** [samolego/FabricTailor#48]
## Server setup: 
`resources_url = https://someplace.io/skins/textures`

## Client operation:
`/skin set player name`

## Result 
Look for (in order)
1. https://someplace.io/skins/textures/name.png
2. MC skins
3. ely.by

## Alternatives
`/skin set name` : not using either 'player', 'upload' or 'url' means you are using the default skin server (as configured on the server config)
`/skin set url name` : if url doesn't contain 'http://' or 'https://' consider it needs to be 'completed' with the server-configured url prefix

**Comment by samolego** [comment]
Shouldn't be too hard actually.
It would probably come out as "https://myskinsite.com/<name>.png

RN I'm in a middle of refactor (threading), so this might need to wait.
Feel free to PR it if you want ;)

**Comment by samolego** [comment]
It's been a while and I'm (finally) implementing this ...

How should slim/default skins be handled?

Perhaps a "custom" category should be better (`/skin set custom <model> <name>`) ...

**Comment by serega404** [comment]
I see you have worked on connecting external skin sources, but I can't figure out how to connect a custom skin server

**Comment by samolego** [comment]
use 2.0.0; set the config option for custom skin server url to wanted protocol (can be also `file://`) and run `/skin set custom <model> <skin_filename>`

**Comment by serega404** [comment]
Can you publish build for 1.18.2?

**Comment by samolego** [comment]
Sorry there've been too many changes to the code :/, I'd rather spent time on other stuff.
