### ISSUE TITLE
[Help] i dont see the npc skin changing {fabric tailor and taterzens}

### ISSUE THREAD

**Issue by UNCQNOWN777** [samolego/FabricTailor#49]
## For skin fetching problems
- [ ] I have tried many times to put a skin on a taterzens npc
using /skin command and the npc was already selected

**Describe the bug**

i selected an npc , type the /skin command , using skins from my files _uploading from my files_, 

it says that the skin was already changed , _succesfully uploaded but the skins doesnt showed or changed ,still the same skin_

also the mod will put a random skin on my npc after i summoned them

**Comment by samolego** [comment]
Which launcher are you using?

**Comment by UNCQNOWN777** [comment]
official launcher ? i mean is there any other launched other than the mojang launcher?

**Comment by samolego** [comment]
There are some cracked launchers that mess with skins. I don't support those, so just checking.

Do you use any other skin mods? Once you relog into the world, does skin update to correct one?

**Comment by UNCQNOWN777** [comment]
sometimes its update to correct one , sometimes it doesn't
oh so those _cracked_ launcher messed up skins?
also why it does always putting up a random skin to my npc
is there a way to turn it off?

**Comment by UNCQNOWN777** [comment]
or is it connected to any online things that make it randomly putting random skins?
i never had those skins btw

**Comment by samolego** [comment]
> also why it does always putting up a random skin to my npc
is there a way to turn it off?

It fetches the skin from player with that name.

**Comment by UNCQNOWN777** [comment]
oh
previously ,it worked fine , when i put any name it will not load any skin
but now
it will auto load a random skin after i summoned the npc

**Comment by UNCQNOWN777** [comment]
also previously im able to change skin either from my files or online
now i can do nothing

**Comment by samolego** [comment]
Have you installed any other mods?

**Comment by UNCQNOWN777** [comment]
yea probably
but i think those mods doesn't affect skins

**Comment by UNCQNOWN777** [comment]
only mods that affecting gameplay like pehkui scale , physics mod ,taterzens ,disguise ,fabrictailor , firstpersonfabric , camera overohaul ,visuality

**Comment by UNCQNOWN777** [comment]
also custom player model

**Comment by samolego** [comment]
Can you try removing custom player model?

**Comment by UNCQNOWN777** [comment]
sure

**Comment by UNCQNOWN777** [comment]
not working but if i playing minecraft with no internet connection , its working well
skin loaded well but i do have an internet connection ,things gone wrong

**Comment by samolego** [comment]
How can you change skins without internet connection :thinking: ?

**Comment by samolego** [comment]
also, can you please post a client log using the mods to replicate the issue?

**Comment by UNCQNOWN777** [comment]
oh now its worked , i have done something about the internet connection
so now its worked well ,thanks for your help ,i really appreaciate it :)
