### ISSUE TITLE
Slim/Alex skins not supported by "upload" command

### ISSUE THREAD

**Issue by Oonicorn** [samolego/FabricTailor#5]
This doesn't seem to be a bug, but when running:
> /skin set upload [file path] 

The selected skin is invariably mapped to the "classic/Steve" model, making skins made for the "slim/Alex" model look really awkward. I'm guessing it would be a pain (if even possible) to detect what model the skin is made for, but would it be possible to add an additional optional argument like:

> /skin set upload [file path] slim

**Comment by samolego** [comment]
Hi, thanks for the suggestion. Yeah, detecting skin model would be ... not really easy. A command however, could be possible to implement.

**Comment by samolego** [comment]
This has been now implemented in `1.3.2`. Thanks for patience :)
