### ISSUE TITLE
[Help] Same skin for all players

### ISSUE THREAD

**Issue by Tok1ra** [samolego/FabricTailor#50]
I need help, some friends and I played on a server and a friend had problems with his skin so I told him about the mod and how to put his skin, but then we all got it instead of just him; I tried to fix it but some players get the change and others don't, using the default skin command it doesn't put "Steve's" skin either but bedrock skins (????)

I tried to remove the mod from the server and its config file and the server would not start without it, please help.

(If there are people using TLauncher with your skins mod, I know you don't offer support for this, but in an unrelated way it happens to all of us).

Any way to uninstall it and get everything back to normal? I understand it does things to player data but I want to avoid having to delete player data.

**Comment by samolego** [comment]
This sounds like a conflict, can you post logs&mods?

**Comment by Tok1ra** [comment]
Mods: https://justpaste.it/8kb6i

Log: https://justpaste.it/3f1ex

**Comment by samolego** [comment]
This log doesn't really help, could you post the one in `.minecraft/logs/latest.log`?

**Comment by Tok1ra** [comment]
Latest.log (Running server, with the mod) https://pastebin.com/eyYV8pRb

If you need it to be when the server is down, do you mind if I do it tomorrow morning? there are several people playing and the last thing I would want is to be in the way after that incident.

**Comment by Tok1ra** [comment]
Ok, taking advantage of the fact that the others went to sleep, this is what the console says when trying to start after deleting the mod (and the config file)

https://pastebin.com/gybeRj07

**Comment by Tok1ra** [comment]
Sorry for your time, I'm dumb.
Your mod must use something similar or integrated special permissions, Toggle PVP uses a permissions mod as a dependency (LuckPerms) and was using your mod as a resource, not having it I had nowhere to continue from. I'm sorry, I really am.

**Comment by samolego** [comment]
FabricTailor bundles permission api.
As pvp toggle doesn't include it, it crashes, but if FT is present, it doesn't for the reason above. You can install luckperms to fix that.

Please post log with mod when you get others to join :).
