### ISSUE TITLE
Slim skin issue

### ISSUE THREAD

**Issue by cowsha** [samolego/FabricTailor#51]
Slim skin changes to normal after i restart game.

**Comment by samolego** [comment]
Please provide more info (as how to reproduce error) & logs. Thanks :)

**Comment by samolego** [comment]
Does any other data dissappaer? Which launcher are you using?

**Comment by samolego** [comment]
It's probably due to tlauncher, since it has some skin patches.
I'm not supporting it due to piracy, so I'm closing this.
