### ISSUE TITLE
[BUG] Doesn't Set Skin Correctly and Puts Random Skin

### ISSUE THREAD

**Issue by AmirAmnoun** [samolego/FabricTailor#52]
Whenever a player tries to set a skin it says that it was successful but nothing changes. Even if the player Leaves and rejoins. However Steve isn't being used, instead a random skin is given every now and then. Usually every 2 days people's skins change randomly. We have tried setting skins using URL and Upload from server files.

Other mods are attached

![image](https://user-images.githubusercontent.com/51382318/159124053-08c3f5ea-3b70-4df2-a4a4-555706e94663.png)

Just a note, the mod used to work even with all these mods installed, it didn't break after installing a new mod, it just happened suddenly. Any help would be appreciated. Thanks in advance.

**Comment by samolego** [comment]
The random element here sounds really strange ... Could you take a backup of one of the players' `dat` file and attach it here? Then wait for the skin change and ddop it here again?
That could help us see what's happening behind tge scenes.

Also, do all players experience the random changes or only a few?

Are all using vanilla launchers?

**Comment by AmirAmnoun** [comment]
We're using TLaunchers, we don't have many people but out of the 2 playing, we're both having problems.
Here's the current .dat file of me. I'll comment again once it updates.

Here's a mediafire link cuz github isn't letting me uplaod `dat `

https://www.mediafire.com/file/ntkgx119uosma13/16206287-73d5-3582-b92a-5513bfb3f99c.dat/file

**Comment by samolego** [comment]
> We're using TLaunchers

That's probably the issue, as tlauncher changes the skin loading.
Some have said to me that there's a toggle for skins in there, but I'm not sure as I won't use it.

As tlauncher is not supported (due to piracy), I'm closing this.
