### ISSUE TITLE
[BUG] server crashes 

### ISSUE THREAD

**Issue by ExVegan0** [samolego/FabricTailor#6]
**Describe the bug**
when i start the server with Fabric Tailor 1.3.1 (all versions) just crash and without do not

**Logs**
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 1
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.

**Are you using any other mods?
fabric-carpet-1.16.3-1.4.11+v200910
hopperOptimizations-1.16.3-0.3.5
lithium-fabric-fork-by-2no2name-mc1.16.3-0.5.9
Phosphor-Mod-Fabric-1.16.3

**Comment by samolego** [comment]
Any reasons why you're using 1.16.3 ..?

Could you append the latest.log? Thanks.

**Comment by ExVegan0** [comment]
Any reasons why you're using 1.16.3 ..?
 
>because it is the newest version with less lag

Could you append the latest.log? Thanks.

>Yeah :D
[latest.log](https://github.com/samolego/FabricTailor/files/5612607/latest.log)

**Comment by samolego** [comment]
`Mod fabrictailor depends on mod {fabric @ [*]}`

You need Fabric API 😉

**Comment by ExVegan0** [comment]
oh thaaaanks <3
