### ISSUE TITLE
[Request] Default skin path configuration

### ISSUE THREAD

**Issue by sisby-folk** [samolego/FabricTailor#60]
Hi there! Local skin upload is my main use case for this mod, but dropping files in .minecraft can get super messy real fast!
It'd be helpful for me if there was a config option that allowed you to set a prefix for the path (e.g. `skins/`) in config, such that any skin in `.minecraft/skins/` can be referred to directly with their filename in the dialogue box.

Thanks!

**Comment by sisby-folk** [comment]
Hey there! I can't find the configuration option for this, is it definitely implemented?

**Comment by samolego** [comment]
Set the `customSkinServer` to `file:///path/to/your/.minecraft/skin/folder`
e.g.
`file://C:/Users/name/AppData/roaming/.minecraft/skins`

**Comment by sisby-folk** [comment]
Ah yeah, this wouldn't work with skin paths relative to .minecraft, would
it? I'm shipping skins in a modpack in `.minecraft/skins`, I'd have no idea
what the absolute path would be.

**Comment by samolego** [comment]
Humm, perhaps try `file://./skins`?
