### ISSUE TITLE
[Suggestion] Add FabricTailor button to `Options -> Skin Customization` menu

### ISSUE THREAD

**Issue by Kneelawk** [samolego/FabricTailor#64]
# The Issue
When searching for a way to update my skin using FabricTailor, my first intuition was to search in the game's existing Skin Customization menu. This was not the correct way to update my skin, and I eventually found the `k` default key-bind for opening the GUI.

# The Suggestion
It might help people looking to customize their skin to also have a button in Minecraft's existing Skin Customization menu that opens the FabricTailor Skin Customization screen.

**Comment by samolego** [comment]
Uh, that's a great idea actually. Thanks :)!
