### ISSUE TITLE
[Suggestion] Luckperms support?

### ISSUE THREAD

**Issue by DBTDerpbox** [samolego/FabricTailor#65]
Would it be possible for the /skin command to have luckperms support? I tried to find the permission using LP's verbose mode, but i found nothing

If the permission exists already, could i know what it is?

thanks

**Comment by samolego** [comment]
Oh I was sure it existed already, lemme check

**Comment by samolego** [comment]
Ah, I already included luckperms in gradle, though haven't implemented anything yet 😅 . Should be trivial though.

**Comment by DBTDerpbox** [comment]
sorry to bother about this again, but do you have the time to add this sometime soon? if not its fine and i'll figure something out

**Comment by samolego** [comment]
CurrentlYou could try usinv https://modrinth.com/mod/universal-perms for now, afaik it adds permission nodes to all commands

**Comment by DBTDerpbox** [comment]
oh thanks! i never knew this mod existed
