### ISSUE TITLE
[Suggestion] API For mod developers

### ISSUE THREAD

**Issue by hypherionmc** [samolego/FabricTailor#66]
Hi there.

I was wondering if there is currently a way, or if not, if a way can be added, to get skins from the mod.

Say I have a server side mod that relays chats to discord, and I want to use the head of a player as an avatar, is there a way to get the URL from the mod for the active skin?

**Comment by samolego** [comment]
Yes, there is exactly this method available :)

**Comment by samolego** [comment]
See https://github.com/samolego/FabricTailor/blob/97a4019ed212c911d2e89e5bb1e4fe11e7b9fb98/src/main/java/org/samo_lego/fabrictailor/casts/TailoredPlayer.java#L76

**Comment by hypherionmc** [comment]
Thanks for the reply :). Does this only work with Mojang skins or also with custom skins (like your mod supports)?

**Comment by samolego** [comment]
It gets you the set skin id, which you can use in combination with https://mc-heads.net/avatar/textureid

**Comment by samolego** [comment]
Yeah, works with fabrictailor skin and falls back to mojang if not set.
