### ISSUE TITLE
[BUG] Minor compatibility issue with Universal Graves

### ISSUE THREAD

**Issue by luni3359** [samolego/FabricTailor#67]
## For skin fetching problems
- [ ] I have tried generating skin manually on [mineskin.org](https://mineskin.org/) and it works there.

## Issue

- [X] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

While using [Universal Graves](https://modrinth.com/mod/universal-graves), any existing or newly created graves render steve if the `/skin clear` command is run even if your account has a skin attached to it. The graves grab the correct skin after using `/skin set player <playername>` with your own name.
![Universal Graves grabbing the wrong skin](https://user-images.githubusercontent.com/16832398/195916470-a3e381aa-0d49-4e9d-af2c-beea90e68103.png)
Here I am using my skin standing next to my grave. Fabric Tailor cleared it back my character to myself but the grave shows steve. I suspect this has to do with the way the skin clearing process works.

**To Reproduce**

1. Die (using the Universal Graves mod)
2. Visit your grave and notice that your skin is yourself
3. Run `/skin clear`
4. You are still yourself (using the skin of your account) but the grave will display steve's skin

**Comment by samolego** [comment]
Does UG fetch right skin without fabrictailor installed?

**Comment by luni3359** [comment]
> Does UG fetch right skin without fabrictailor installed?

Yes. I've done some more testing and it looks like graves get your player skin correctly after leaving and rejoining the server. I'm not sure if this is a Fabric Tailor problem anymore.
