### ISSUE TITLE
Replay Mod & Skin Changing Incompatibility

### ISSUE THREAD

**Issue by KiloPetraGames** [samolego/FabricTailor#68]
I have noticed a compatibility issue with the Replay Mod. Whenever, my player switches skins using the GUI, nothing changes in game, all of my player's held items and equipped armor vanish from view in the replay.

This can be resolved if all item/armor are individually re-equipped after changing skins. However, this is a consistent issue that will always happen after changing skins in FabricTailor.

As an example, I will be wearing full iron armor and holding a torch, but the second I change skins, everything vanishes and my character looks like they are wearing no armor, and holding no torch. My character is still technically holding/wearing these items, but they're no longer visible unless I re-equip each individual item after changing my skin while recording.

**Comment by samolego** [comment]
Thanks for report. I think it's due to not sending all the packets upon gameprofile change ...

**Comment by KiloPetraGames** [comment]
> Thanks for report. I think it's due to not sending all the packets upon gameprofile change ...

Is there anything I could change on my end to fix it, or is it something that could be resolved in a patch?

**Comment by samolego** [comment]
No, that's up to the mod.
