### ISSUE TITLE
[BUG] Compatibility issue with ETF (Entity Texture Features)

### ISSUE THREAD

**Issue by billyp673** [samolego/FabricTailor#69]
## Issue

- [ ] When changing skins with ETF installed, the skin doesn't update until you relog.

**Additional context**
One of the features of ETF is that it can render extra effects (such as emissive textures) on your skin, the data for which is saved within the skin file. This functionality in of it self works fine with FabricTailor, it's just the updating of the skin for the client that is postponed until a relog takes place.

**Comment by samolego** [comment]
Humm, that might be ETF only issue, not sure.

**Comment by billyp673** [comment]
Having a glance at their github repo, [especially this issue](https://github.com/Traben-0/Entity_Texture_Features/issues/112), I'd say you're probably right...

**Comment by Traben-0** [comment]
this has been resolved in ETF release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0

**Comment by billyp673** [comment]
Sweet as

**Comment by billyp673** [comment]
Thanks for letting me know
