### ISSUE TITLE
Error when using the URL and whit the Pathway. 1.16.3

### ISSUE THREAD

**Issue by RedSteve69420** [samolego/FabricTailor#7]
It give me an error when i try to change skin whit the URL and whit the pathway in my pc.
The url and the pathway are rigth.

Im using the replay mod whit fabric API

**Comment by samolego** [comment]
Could you provide a skin url which gives you an error? Thanks.

**Comment by RedSteve69420** [comment]
file:///C:/Users/mikes/OneDrive/Desktop/Video_photo/Skin/red.png

**Comment by samolego** [comment]
This is your local file, not URL?

You should only use `C:/Users/mikes/OneDrive/Desktop/Video_photo/Skin/red.png` in path, e.g. ```/skin set upload C:/Users/mikes/OneDrive/Desktop/Video_photo/Skin/red.png``` without the `file:///`

**Comment by RedSteve69420** [comment]
ok, now i try it, thanks!

**Comment by RedSteve69420** [comment]
ok it work, thanks
