### ISSUE TITLE
[Help] Where does FabricTailor store the cached skins?

### ISSUE THREAD

**Issue by Ranzeplay** [samolego/FabricTailor#71]
I need help. I wonder how the mod stores the custom skins the player wanted.

**Comment by MGJerry** [comment]
From what I've seen, regardless of singleplayer or multiplayer, it's stored in the each player's .dat as "fabrictailor:skin_data" (so yes, you can have different skins for each world and server).

You can check it in "<minecraft-folder>/saves/<world-name>/playerdata/<uuid>.dat" (client) or "<server-root>/world/playerdata/<uuid>.dat" (server) with a text editor, or some compatible program like [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases), but it mostly look like this:

![image](https://user-images.githubusercontent.com/85227828/211701358-bbb8e901-a86a-4085-affa-362e16339a3e.png)

Or if you have it installed client-side, you could take a look at this #60

**Comment by Ranzeplay** [comment]
Thank you very much! So sorry that I didn't view the source code before I open the issue.

**Comment by Ranzeplay** [comment]
That's exactly my case! I wonder if I could build a Minecraft scene in Blender, but when I asked my friend for his skin, he lost it!
