### ISSUE TITLE
[BUG] Can't have skin and cape at the same time on server

### ISSUE THREAD

**Issue by Kafekie** [samolego/FabricTailor#73]
So when I set skin with fabric tailor menu and then I try to set cape my skin sets to steve, but with cape.
And when I set skin again cape disappears.
In singleplayer I don't have this problem, server is on fabric, has fabric tailor
Fabric 1.19.2

**Comment by samolego** [comment]
Humm, that's quite strange. I'll have a look into it.

**Comment by samolego** [comment]
fixed in 2.1.1

**Comment by samolego** [comment]
I'm sorry but I don't really do backporting
