### ISSUE TITLE
[BUG] The keyboard shortcut does not work

### ISSUE THREAD

**Issue by QueenUlyana** [samolego/FabricTailor#77]
The keyboard shortcuts "Ctrl+C and Ctrl+V" do not work. I can't insert a link or anything else, it works everywhere except for your mod. Rather, the windows of your mod where you need to insert links and so on.

**Comment by QueenUlyana** [comment]
But that's not all, skins by nickname don't work.

**Comment by QueenUlyana** [comment]
@samolego

**Comment by samolego** [comment]
"They work for me" 😅.

Which version? Launcher?

**Comment by QueenUlyana** [comment]
> 

1.19.4 https://github.com/UltimMC/Launcher

**Comment by samolego** [comment]
> UltimMC
This is a "cracked" version of a popular Minecraft launcher that lets you play the game without a Microsoft account

I'm sorry, but I can't support cracked launchers. It's the reason for skins not working.
Not really sure what's causing the copy paste failure.
