### ISSUE TITLE
[Issue] Blocked domain

### ISSUE THREAD

**Issue by aladairmaxwell** [samolego/FabricTailor#79]
Hi! Been using a licenced Minecraft on Fabric server with mod installed and offline mode turned on. Trying to set a cape using K button menu window resets my skin to default and doesn't apply cape. What to do?

**Comment by samolego** [comment]
Please provide logs both from server & client. Which version? Which launcher? Do you have mod installed on both ends?

**Comment by aladairmaxwell** [comment]
Yes, I do.

I'm using Microsoft Launcher. I'm using latest version on 1.20.1 version (both server and mod).

Which log do I need to provide? (logs/latest.log)

**Comment by samolego** [comment]
Yeah, both client and server latest logs

**Comment by aladairmaxwell** [comment]
[latest-client.log](https://github.com/samolego/FabricTailor/files/12077499/latest-client.log)
[latest-server.log](https://github.com/samolego/FabricTailor/files/12077500/latest-server.log)

**Comment by Revod** [comment]
> Hi! Been using a licenced Minecraft on Fabric server with mod installed and offline mode turned on. Trying to set a cape using K button menu window resets my skin to default and doesn't apply cape. What to do?

its happen to me too in my 1.20 fabric server, skins works but cape doesn't

**Comment by samolego** [comment]
"Textures payload contains blocked domain:"

**Comment by samolego** [comment]
You need to allow discordapp in the config

**Comment by Revod** [comment]
> You need to allow discordapp in the config

Make sense, I opened the config file on my server and saw the allowed url, downloaded the cape and uploaded to Imgur and worked, but I tested and my other friend didn't saw it, is just client side? (that im the only one that im going to see the cape) im using my premium mc skin, just wanted to change my migration cape to something else

**Comment by samolego** [comment]
The allowed skins is clientsided. Make sure your friend has imgur in the array as well

**Comment by aladairmaxwell** [comment]
Yeah, thank you! I put a cape via Imgur and it worked

**Comment by Revod** [comment]
> The allowed skins is clientsided. Make sure your friend has imgur in the array as well

Yeah I know, I mean I can see my friends skins and the config file is the default so is the same as the server and my mine on Prism, but the only thing that we can't see are the capes, but maybe still something that I need to figure out, thank you anyway, is one of my favs mods
