### ISSUE TITLE
[BUG] Server Crash on Startup

### ISSUE THREAD

**Issue by Mino-tan** [samolego/FabricTailor#8]
**Describe the bug**
The new Fabric API update (0.28.0) seems to be incompatible with the latest fabrictailor version(1.3.2) in curseforge.

**To Reproduce**
1. Install Fabric API and Fabric Tailor
2. Attempt to launch the server
3. Server crashes

**Logs**
Copy-pasted log: https://paste.ee/p/x6dgY
 Original log: https://mclo.gs/WRLBfCu

**Are you using any other mods?**
No. I basically trimmed down my mod list to pinpoint the issue. Left with these two mods here.
**Additional context**
I tried getting the crash-report but it doesn't seem to create it. The original log as stated above is the only thing that https://mclo.gs shows what my panel shows as well. I resorted to copying the console manually, instead.
The server I'm using for testing is Aternos. Used Java 8 OpenJDK in their option when launching the server.

**Comment by samolego** [comment]
Humm, seems like FAPI has removed an accessor that I was using. I'll look into it. Thanks for reporting.

**Comment by Mino-tan** [comment]
Ohh. Thanks for the quick response and quick fix!
