### ISSUE TITLE
1.20 + Connector compatibility markings

### ISSUE THREAD

**Issue by sisby-folk** [samolego/FabricTailor#80]
Hi hello! The [modrinth page](https://modrinth.com/mod/fabrictailor/versions) currently has manually specified featured versions, which hide the compatible versions for 1.20 a bit. It would be great if the featured versions could be cleared so it could always show the latest available versions.

That's a boring lone thing to write an issue about - so actually i'm also here because tailor runs flawlessly on [connector](https://modrinth.com/mod/connector)+[ffapi](https://github.com/Sinytra/ForgifiedFabricAPI)

![image](https://github.com/samolego/FabricTailor/assets/55819817/f181dfcd-fdde-4789-9cd0-4dbfc353bb98)

even using the fabric tailor switchy module:

![image](https://github.com/samolego/FabricTailor/assets/55819817/1cf80107-fe41-4821-ac5e-afb6fbae99d1)

if desired, you can mark this compatibility explicitly. There's no such thing as loader-specific dependencies on modrinth ([yet](https://github.com/modrinth/labrinth/issues/700)), so i default to just putting a connector+ffapi note in the description
![image](https://github.com/samolego/FabricTailor/assets/55819817/cd4746d0-4fe2-4599-970a-4e4a99c9d59f)

Thanks for the great mod as always!

**Comment by samolego** [comment]
I'm not even sure why specific version is featured, I thought it was always the latest 😅.

Thanks for the connector tip!

**Comment by sisby-folk** [comment]
yep you should be able to manually unselect "feature" in every version and it'll go back to showing latest

**Comment by samolego** [comment]
Done, thanks!
