### ISSUE TITLE
[BUG] Error (kicks out of world/server) when skin/cape changed and immersive portals is installed.

### ISSUE THREAD

**Issue by teknixstuff** [samolego/FabricTailor#81]
## For skin fetching problems
~~- [ ] I have tried generating skin manually on [mineskin.org](https://mineskin.org/) and it works there.~~
Not relevent to this issue.

## Issue

- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

Internal Exception: java.lang.IllegalArgumentException: Maybe a mod is trying to add entity in a non-server thread. This is probably not ImmPtl's issue

**To Reproduce**

1. Install Immersive Portals + Fabric Taylor
2. Run game
3. Change skin via GUI
4. Kicked with error

**Logs**

Log file contains no relavant info.

*Are you using any other mods?*

**Additional context**

No additional context available.

**Comment by teknixstuff** [comment]
Further info will be added when I have time

**Comment by samolego** [comment]
Thanks for reporting. This might take a while, as I'm currently off with the modding, sorry.

**Comment by Dumpling00** [comment]
Trying to bump this, hoping for a fix now that I noticed more activity. It's still very much a problem for fabric 1.20.1 - Can we please have a fix?

**Comment by samolego** [comment]
There sadly won't be a fix for old versions from my side, sorry.

**Comment by Dumpling00** [comment]
That's fair and all, but I have a question then - is there a fix that's been implemented in a newer version? If so could I please be pointed to it? And could we be allowed to fork and backport the fix ourselves?

**Comment by samolego** [comment]
I don't know of any working fix, but you're free to fork the code! Mod is LGPLv3 licensed, so the only limitation is that if you publish your version publically, you must also publish the source code.
