### ISSUE TITLE
[HELP] Skin layer rendering issue

### ISSUE THREAD

**Issue by YkVox** [samolego/FabricTailor#82]
- [✓] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

Hello !
i'd like to state that this is not a bug per se, since it is not specific to FabricTailor but i'm looking for clues to fix a conflict
it occurs with any cape or skin changing mod combined with the Gigeresque and/or Frostiful mods
using both of these on a server does restore and apply skins but not the outer layer, wearables (any armor) and items in the offhand

i may be posting in the wrong place, but i don't really have another way (gigeresque's creator refused to help me on this)
so what i'm looking for (or at least i'm hoping to look for) is where the skin replacement method conflicts with these mods ? knowing that information i could try and fix the issue

![image](https://github.com/cybercat-mods/gigeresque/assets/61479000/ee37b47e-17d8-4a16-8220-7f7107750384)

the issue is encountered with:
-Kappa
-Capes
-SkinRestorer
-FabricTailor (hi!)

thank you for your time, and sorry again if this isn't the kind of issue you want to have here
have a wonderful day

vox

**Comment by samolego** [comment]
Sorry, could you elaborate, write what's going on in more detail?

**Comment by YkVox** [comment]
So while combining gigeresque or frostiful mods with fabric tailor on a server, the skin is correctly applied but flat (without the second layer), any armor equipment is invisible if you are not present when another player equips it, any offhand held item will not appear

this is all i know, of course it's particularly frustrating when trying to fight another player because you don't know wether they're blocking or not(if they do have a shield on) or what kind of armor they're wearing if they're indeed wearing one

**Comment by samolego** [comment]
Are there any special logs in console?

**Comment by YkVox** [comment]
no, both server and vanilla console are showing regular logs...

**Comment by samolego** [comment]
Sorry to say, but then it's probably the other's mod issue, seeing that it conflicts with other skin mods as well ...

**Comment by YkVox** [comment]
yeah.. still thanks for the help, have a good day :)
