### ISSUE TITLE
[BUG] Skins not showing

### ISSUE THREAD

**Issue by venomshaggy123** [samolego/FabricTailor#83]
I made a fabric server, and for testing installed mods, I opened 2 Minecraft fabric instance(one in SKlauncher other in Tlauncher) and connected to the server. Once I entered /skin command and set my custom skin on SKlauncher instance it only change into launcher default or steve or alex. In Tlauncher instance its only steve and alex (sometimes steve skin with missing texture)(and I tried both TL skin on and off). And I tried player Dream and jeb_ also example in your wiki. Nothing works!!!!! Please help me!!! 

I'm running server with 
lithium,
starlight, 
FPSreducer, 
C2ME, 
easyauth, 
memoryleakfix, 
krypton, 
fabrictailor,
ferritecore, 
plasmavoice, 
clumps. 

And on PC with 
Sodium, 
iris, 
fabrictailor, 
plasmavoice

(sorry for any spelling mistakes)

**Comment by samolego** [comment]
Tlauncher is not supported. Please follow issue template.
