### ISSUE TITLE
[BUG] after one day of playing, the skin stopped changing

### ISSUE THREAD

**Issue by LasTTy11** [samolego/FabricTailor#84]
after one day of playing, the skin stopped changing and the mod itself stopped working, I stopped seeing other people's skins on the server with this mod I tried a bunch of launchers, nothing helped

**Comment by samolego** [comment]
Please describe the issue with more details. Wdym by stopped changing? Fabrictailor saves the player skin so you need to clear it to get your default one from minecraft.net

**Comment by LasTTy11** [comment]
completely skin, it was reset and when I try to change it, it doesn’t change for me, but for my friends it changes, I also don’t see the skins of my friends in this mod, that is, the skins that they put in this mod

**Comment by samolego** [comment]
Sounds like a launcher problem / mod conflict problem
