### ISSUE TITLE
[BUG] 1.20.2 Release not being detected by server

### ISSUE THREAD

**Issue by Zayni2k** [samolego/FabricTailor#86]
## Issue

- [✔] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

*Are you using any other mods?*
- Fabric api v0.91.2

**Describe the bug**

A clear description of what the bug is.
- My 1.20.2 Fabric Server does not detect release 2.2.1 of Fabric Tailor and gives me a default skin in the server.
- The mod and keybind does work on client side and in singleplayer.
- Attempting to use command "/skin set player" does nothing.
- Using the keybind "K" on my Fabric Server gives me an error in chat that says "Fabric Tailor Fabric Tailor mod is sadly not installed on this server."
- Pressing "K" again will open up the Client menu but nothing happens even if I try changing my skin from there.
- I've tested the mod on 1.20.4 version of Minecraft and Fabric Server and it works perfectly fine.

Is this an issue on my end? Seems pretty unlikely but then again, I haven't been able to find any reports about it.

## Edit:

Seems like the issue was on my end after all. I had to do a clean set up of the 1.20.2 Fabric Server using the [installer](https://fabricmc.net/use/installer/) along with the launch scripts it provides and it started working properly.

**Comment by samolego** [comment]
1.20.2 changed client-server communications, sadly I only implemented it later ...

**Comment by Zayni2k** [comment]
> 1.20.2 changed client-server communications, sadly I only implemented it later ...

Ah, I see, so would you be able to get it working again or is that not possible?

**Comment by samolego** [comment]
Oh I see, mod wasn't even loaded on server :)
