### ISSUE TITLE
[BUG] Cape fetch worked only once

### ISSUE THREAD

**Issue by xibau** [samolego/FabricTailor#89]
Cape fetch only worked once, it since only display the first cape I ever gave it the link, whatever link I am giving.
I tried to clear skin or re start game and it still display the first cape

1. Paste a cape, apply
2. Do the same for another cape
4. Cape stay as first one

**Logs**

no errors related to fabric Tailor.

*Are you using any other mods?*
yes but QOL ones, sodium iris etc

**Additional context**
Prism Launcher, linux (openSUSE, KDE)

also, not related but if you give an empty url then apply, the game will crash

**Comment by samolego** [comment]
Hum, that's strange. Could you please specify your mc version as well? Thanks :)

**Comment by xibau** [comment]
1.20.4

**Comment by samolego** [comment]
Cannot reproduce with new version.

**Comment by xibau** [comment]
I tried on 1.20.6, fresh instance, only sodium.
I can confirm the bug is still present, and even though it's a new instance it still display the first cape it ever fetched.

Prism launcher, openSUSE KDE

Feel free to ask for additional details

**Comment by samolego** [comment]
Tried
https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/51/MINECON_2013_Cape_(texture).png
then
https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cd/Mojang_Classic_Cape_(texture).png
after that
https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/af/Bacon_Cape_(texture).png

All worked. Might be an incompatibility or wrong cape texture.

**Comment by xibau** [comment]
For some reason there are cape that work with the full wikia URL, but most of them need the link cleared after the image name. Sorry for the loss of time and thanks for your assistance ! (btw local cape folder when :))

**Comment by samolego** [comment]
It must be an URL if I want to keep it server-compatible ...
