### ISSUE TITLE
Feature suggestion: limit command to ops

### ISSUE THREAD

**Issue by LauraLovesRaccoons** [samolego/FabricTailor#91]
Sorry to bother you,

First of this is for a server use case,

and it would be a great idea if you could restrict the command to op level 2 and if that is active break the mod on the client side (so that it gives a warning message).
An additional entry in the config.json called for example: 
  "// Restrict access to ops (level 2+) and disable clientside interaction": "(default in singleplayer&server: false, activation for server: true)",
  "restrict_access_to_ops": true,
  and if you don't have the necessary permissions (client-side mode) you just get a message, like: server only allows skin changing via commands or ops.
The use case for this would be for an event where you can as an example zombify a player and in that case a datapack or command block could run the command if player dies to a zombie they will get a zombie skin.
My knowledge comes from small datapacks so I'm not sure how to implement something like this. The easiest solution for my use case would be restricting the command as a mod override or hardcoded (with no toggle).
I also heard about the suggestion to allow to change skins from players that are offline which is also kinda cool for events, but that one might be even more difficult to implement.

I hope this helps and in case I know how to do my feature suggestion as a hardcoded option I'll let you know (but I'm going in clueless).

**Comment by LauraLovesRaccoons** [comment]
small oversight I've used the 1.19.3 version of the mod, so this post might be outdated

**Comment by samolego** [comment]
Hi there!
There's even more advanced system already: you can disable / enable permissions for setting skins:
```
fabrictailor.command.skin.<set|clear>
```

**Comment by samolego** [comment]
I'd recommend using luckperms for applying permissions, you can get it from curseforge / modrinth.

**Comment by LauraLovesRaccoons** [comment]
Thank you for the suggestions and sorry again for not double checking which version I ran.
You might add your first post to the documentation somehow as I didn't see your first command on neither the github wiki, nor the curseforge page and neither the modrinth page.
For permissions if luckperms does it, then there is no reason to implement it, just perhaps mention it in the documentation as well.
I leave this "bug" report open so you can decide if this is a suggestion for the documentation.

**Comment by LauraLovesRaccoons** [comment]
Well I think the update you made to the readme will help some players :)
