### ISSUE TITLE
[BUG] HD skins not working (1.20.1 release)

### ISSUE THREAD

**Issue by Lakeno** [samolego/FabricTailor#96]
HD skins (128x128) dont work as described in the mod's page. When trying to upload the skin via this [link](https://raw.githubusercontent.com/Lakeno/images/main/Link%20high%20res.png), a red warning saying "You have to provide URL, player's name or file of the skin you want".

This link should be readable, as this [another skin](https://raw.githubusercontent.com/Lakeno/images/main/Link.png) from the same source loads fine, and the HD skin is in the correct format.

-not using tlauncher
-isolated the mod

Any help is apreciated, thanks for this super helpful mod!

**Comment by samolego** [comment]
Just to clarify, you're using mod to set skin right?

**Comment by Lakeno** [comment]
Yes. I'm using "/set skin URL classic [URL]

**Comment by samolego** [comment]
You cannot set HD skin via command. You need to use the client mod.

**Comment by samolego** [comment]
That's because you won't see hd skin without client mod, so then why bother using the command to change it if you have GUI?

**Comment by samolego** [comment]
Thanks for deepdive. I'm not sure what's happening, can you post logs as well?

**Comment by Lakeno** [comment]
Ok

load in game -> create superflat world -> open GUI -> load 64x skin via URL -> try to load 128x skin via URL and fail (3x) -> load 64x skin via filepath -> try to load 128x skin via filepath and fail (2x) -> alt f4

[latest.log](https://github.com/samolego/FabricTailor/files/14780619/latest.log)

**Comment by samolego** [comment]
Thanks. Will need to debug this when I have time.

**Comment by samolego** [comment]
Fixed in 2.4.0
