### ISSUE TITLE
Can`t set up skins even with proper internet connection

### ISSUE THREAD

**Issue by LegendaryMouse** [samolego/FabricTailor#97]
![image](https://github.com/samolego/FabricTailor/assets/134811008/d3411dfe-835e-4b67-a88f-2737ecca727c)

/skin set URL classic "https://cdn.discordapp.com/attachments/1202616582841434132/1221545557164556459/123.png?ex=6612f7f4&is=660082f4&hm=a2bd6aa1dd14eea76cbc226de46dc58e6feeb5646d98f5498dac16f773cfa0b4&"

_Originally posted by @LegendaryMouse in https://github.com/samolego/FabricTailor/issues/95#issuecomment-2016923487_

**Comment by samolego** [comment]
Can you paste the error? Please add the logs as well.

**Comment by LegendaryMouse** [comment]
![image](https://github.com/samolego/FabricTailor/assets/134811008/45b9f415-ef4d-4adf-97fb-e8cfc62f15a3)
![image](https://github.com/samolego/FabricTailor/assets/134811008/0ad03e23-3d90-4bb6-8b30-f906cea69713)

**Comment by LegendaryMouse** [comment]
console shows no error

**Comment by magmamir** [comment]
As far as i know discord has recently limited the lifetime of links to files. I'm not a developer of this mod, and i'm not 100% sure, but maybe that's the problem.

**Comment by LegendaryMouse** [comment]
> As far as i know discord has recently limited the lifetime of links to files. I'm not a developer of this mod, and i'm not 100% sure, but maybe that's the problem.

imgur and other services also don`t work

**Comment by MGJerry** [comment]
![2024-04-02_08 34 58](https://github.com/samolego/FabricTailor/assets/85227828/49f6d4c2-29ae-41f2-9b43-0d9125863faa)

Seems fine to me...
Command used: /skin set URL classic https://cdn.discordapp.com/attachments/1202616582841434132/1221545557164556459/123.png?ex=6612f7f4&is=660082f4&hm=a2bd6aa1dd14eea76cbc226de46dc58e6feeb5646d98f5498dac16f773cfa0b4&

**Comment by LegendaryMouse** [comment]
> ![2024-04-02_08 34 58](https://private-user-images.githubusercontent.com/85227828/318612388-49f6d4c2-29ae-41f2-9b43-0d9125863faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODQ4NTcsIm5iZiI6MTcxMjA4NDU1NywicGF0aCI6Ii84NTIyNzgyOC8zMTg2MTIzODgtNDlmNmQ0YzItMjlhZS00MWYyLTliNDMtMGQ5MTI1ODYzZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE5MDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4OGMxMjU1MjQ3MTVkOTRhMmVmMzk1OTllNjE2MDVjOTllZjAzZjQ0YmFmMmE4NDI2NjNhOTRjODI0MzZkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fYQwmPgIFocRuKMkH7veZc7j7SzY15LjL7m73m5wXmc)
> 
> Seems fine to me... Command used: /skin set URL classic https://cdn.discordapp.com/attachments/1202616582841434132/1221545557164556459/123.png?ex=6612f7f4&is=660082f4&hm=a2bd6aa1dd14eea76cbc226de46dc58e6feeb5646d98f5498dac16f773cfa0b4&
> 
> Edit: the problem lies within the double quotes you put around the url, just don't add it

![image](https://github.com/samolego/FabricTailor/assets/134811008/a9364759-a806-4bc9-961a-570aee590a57)

well, tried it without quotes, got same error
